import type { Metadata } from "next";
import { Red_Hat_Display, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/provider";
import { ToastProvider } from "@/components/ui/toast";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.variable} ${poppins.variable} antialiased`}
      >
        <ToastProvider>
         
            <Providers>{children}</Providers>
        
        </ToastProvider>
      </body>
    </html>
  );
}
